name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 添加權限設定
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Deploy to Cloud Run"
        run: |-
          gcloud run deploy weather-app \
            --source . \
            --project weather-app-demo-11 \
            --region asia-east1 \
            --platform managed \
            --allow-unauthenticated
