name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov requests-mock

      - name: Run tests
        run: |
          pytest tests/ --cov=./

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          service_account: "github-action-demo@weather-app-demo-11.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Deploy to Cloud Run"
        run: |-
          gcloud run deploy weather-app \
            --source . \
            --project weather-app-demo-11 \
            --region asia-east1 \
            --platform managed \
            --allow-unauthenticated
